### ISSUE TITLE
IEP04 - Internal Data Format: Meta Information and Data Exchange - UUID

### ISSUE THREAD

**Issue by adulau** [certtools/ieps#1]
Not sure I fully understand the document and proposed format.

The UUID mentioned is the UUID of the IntelMQ instance or a unique UUID per message?

I would recommend to have a unique UUID per IntelMQ instance.

**Comment by aaronkaplan** [comment]
> On 22.04.2021, at 11:48, Alexandre Dulaunoy ***@***.***> wrote:
> 
> 
> Not sure I fully understand the document and proposed format.
> 
> The UUID mentioned is the UUID of the IntelMQ instance or a unique UUID per message?

I think it's the UUID per message as far as I understood it.

> 
> I would recommend to have a unique UUID per IntelMQ instance.

That would be an originator (which IntelMQ instance created this event).

**Comment by aaronkaplan** [comment]
By the way Alexandre, I see an opportunity to map to MISP formats...

**Comment by adulau** [comment]
What's the use of the UUID per message? Is it uniquely generated (like a Message-Id)? or is it fixed per content to avoid duplicate processing?

**Comment by aaronkaplan** [comment]
See IEP003. It's like linking MISP objects/attributes to each other in MISP

| IntelMQ | MISP |
--------|-------
| Event ( a dict) |   MISP object | 
| key  in a Event | Attribute | 
| UUID in IEP003 | UUID of the MISP object | 
| IntelMQ instance UUID | UUID of the MISP instance |

**Comment by aaronkaplan** [comment]
> What's the use of the UUID per message? Is it uniquely generated (like a Message-Id)? or is it fixed per content to avoid duplicate processing?

Yeah, good question if the UUID is a hash of the whole message or just an idea.

**Comment by ghost** [comment]
> What's the use of the UUID per message? Is it uniquely generated (like a Message-Id)? or is it fixed per content to avoid duplicate processing?

hash would be possible, but does not make sense in this regard. The format of the UUID is open for disussion

**Comment by ghost** [comment]
In the hackathon the conclusion was to:

- add UUID per IntelMQ instance
- add UUID per event
- add type for UUID to UUID linking

To get this done, we are still waiting for your input on the exact specification.

I'll start with this first proposal (let's call it "A"):

```
{
    "uuid": {
        "origin": "<originator's UUID if set in the configuration>"
        "event": "<random UUID, generated on event creation>",
        "links": [
            {
                "link-type": "TBD",
                "links": [
                    "uuid1",
                    "uuid2",
                ]
            }
    },
    ...
}
```

ping @aaronkaplan @adulau @certbe-trey @otmarlendl @pharook @certtools/intelmq-maintainers

**Comment by bernhardreiter** [comment]
The current IEP04 does not describe the use cases in enough detail to comment on the two(?) unique identifiers that are being discussed.

So in general:


Calling them UUID only makes sense, if you want to use the standard https://en.wikipedia.org/wiki/Universally_unique_identifier.

* If the aim is to log origin, then I suggest to use a domain name (fqdn), which is unique. (This is how email addresses or some module namespaces for go or java languages do it.)
* If the aim is deduplication (which is the only use-case I could see at a glance in IEP04) then define what the real contents is and each application can then just see, if it had the contents by using a checksum (hash). No need for a unique identifier per each event, as far as I can see.

**Comment by pharook** [comment]
> I'll start with this first proposal (let's call it "A"):
> 
> ```
> {
>     "uuid": {
>         "origin": "<originator's UUID if set in the configuration>"
>         "event": "<random UUID, generated on event creation>",
>         "links": [
>             {
>                 "link-type": "TBD",
>                 "links": [
>                     "uuid1",
>                     "uuid2",
>                 ]
>             }
>     },

The question is what information the link really needs to convey, and how easy or hard the access would be. My guess (based on our experience) is you (or better software, bots) will want to access links based on their type - either you want the Id of the event itself, or "related" links, or "group" links, and so on. This proposal (A) forces the software to have to iterate over all the links and filter out the ones it needs. I'd go for (in my opinion) more KISS mode, where link type is the object key. Also, you may want to incorporate (or just make available, I guess this will rise up from usecases), links to other systems, which may not be uuid.

```
"meta": {
    ...
    id: "22e3d57e-a8f6-11eb-afb2-2fae0e83f6f9",
    related: ["342a94d0-a8f6-11eb-b55d-3fbbafa57450", "d256379e-a8f7-11eb-8f63-2fb9e3acb5fb"],
    group: ["ed4e10f8-a8f7-11eb-baaa-33efc701ab52"],
    alternate: ["RT#1234", "cesnet-certs:fed4740c-a8f7-11eb-9e47-efc1855d7a66"]
    ....
}
```

Key (aka "type") names are just examples. 

Also, question is whether meta and payload namespaces are necessary altogether, during the years I've got the tendency to dislike unnecessary nesting. :) But of course less KISS and more tidiness may make sense sometimes.

**Comment by ghost** [comment]
another reminder @aaronkaplan @adulau @certbe-trey @otmarlendl @pharook @certtools/intelmq-maintainers to join the discussion. In the hackathon we've agree to finish the specification by mid of last week.

@pharook composed an extensive list of use-cases, see his post on the mailinglist: https://lists.cert.at/pipermail/intelmq-dev/2021-April/000478.html

> Also, question is whether meta and payload namespaces are necessary altogether, during the years I've got the tendency to dislike unnecessary nesting. :) But of course less KISS and more tidiness may make sense sometimes.

It could also be like this:
```
{
     "source.ip": "10.0.0.1",
     ....
    "_meta": {
        "id": "22e3d57e-a8f6-11eb-afb2-2fae0e83f6f9",
        ....
    }
}
```
Or:
It could also be like this:
```
{
     "source.ip": "10.0.0.1",
     ....
    "_id": "22e3d57e-a8f6-11eb-afb2-2fae0e83f6f9",
    ....
}
```

**Comment by waldbauer-certat** [comment]
I'd suggest to use the nested idea aswell here. IMHO data looks much cleaner to new developers & we dont have collisions in near future.

> related: ["342a94d0-a8f6-11eb-b55d-3fbbafa57450", "d256379e-a8f7-11eb-8f63-2fb9e3acb5fb"],

I'd personally like the idea of linking events together, but this adds a lot of logic to intelmq itself. Which data point is used to check if an event or report is related to another? I'd follow the git logic. Using parent uuids & current uuid, so you can build an event chain & you can trace those events back on demand with a "git-like" history? But chaining multiple events with chaining might end up in data races :thinking:

**Comment by ghost** [comment]
> I'd suggest to use the nested idea aswell here. IMHO data looks much cleaner to new developers & we dont have collisions in near future.
> 
> > related: ["342a94d0-a8f6-11eb-b55d-3fbbafa57450", "d256379e-a8f7-11eb-8f63-2fb9e3acb5fb"],
> 
> I'd personally like the idea of linking events together, but this adds a lot of logic to intelmq itself. Which data point is used to check if an event or report is related to another? I'd follow the git logic. Using parent uuids & current uuid, so you can build an event chain & you can trace those events back on demand with a "git-like" history? But chaining multiple events with chaining might end up in data races thinking

When creating copies of message (`self.new_event(original_event)`) we can set the relationship accordingly. For the reading/interpretation step, the use-cases are in other systems/databases only - as of now.

**Comment by pharook** [comment]
> It could also be like this:
> 
> ```
> {
>     "_meta": {
> ...
>     "_id": "22e3d57e-a8f6-11eb-afb2-2fae0e83f6f9",
> ...
> ```

We allow arbitrary keys in Idea, so users can add whatever keys they need, and it's often used for internal (enrichment) data, into underscore prefixed keys. So we easily know, what to strip when sending event further. However, I'm not sure if that's even applicable - whether IntelMQ even allows for arbitrary keys, not specified in harmonisation?

**Comment by pharook** [comment]
> > related: ["342a94d0-a8f6-11eb-b55d-3fbbafa57450", "d256379e-a8f7-11eb-8f63-2fb9e3acb5fb"],
> 
> I'd personally like the idea of linking events together, but this adds a lot of logic to intelmq itself. Which data point is used to check if an event or report is related to another? I'd follow the git logic. Using parent uuids & current uuid, so you can build an event chain & you can trace those events back on demand with a "git-like" history? But chaining multiple events with chaining might end up in data races thinking

Note that if you link only prev/next event, if you lose just one event on the go, you'll lose the link to the rest of the chain.

I'd suggest to link all the following events to the first event (beginning of the chain), or to the same "group identifier", as if you lose one of the events, the link to all others is maintained. (In Idea I've defined GroupID for that, however it's not yet in official doc.)

Also note that by grouping by linking, the recipient never really knows it has all the data (complete set).

**Comment by pharook** [comment]
> But chaining multiple events with chaining might end up in data races thinking

Ah, forgot to note that this might also be naturally solved (or at least mitigated, I surely didn't think all the possibilities through) by group-linking or front-linking.

**Comment by ghost** [comment]
> We allow arbitrary keys in Idea, so users can add whatever keys they need, and it's often used for internal (enrichment) data, into underscore prefixed keys. So we easily know, what to strip when sending event further. However, I'm not sure if that's even applicable - whether IntelMQ even allows for arbitrary keys, not specified in harmonisation?

No, IntelMQ forbids arbitrary keys as one of its key concepts as an advantage over AbuseHelper, which allowed any data anywhere.

**Comment by pharook** [comment]
> > We allow arbitrary keys in Idea, so users can add whatever keys they need, and it's often used for internal (enrichment) data, into underscore prefixed keys. So we easily know, what to strip when sending event further. However, I'm not sure if that's even applicable - whether IntelMQ even allows for arbitrary keys, not specified in harmonisation?
> 
> No, IntelMQ forbids arbitrary keys as one of its key concepts as an advantage over AbuseHelper, which allowed any data anywhere.

Thought so. Even then I would be wary to use underscore prefixes - I'd reserve that for some possible use-case in the future which would not be solvable by namespacing, or be orthogonal to namespacing. Underscore can convey just one precious bit of information, possibly usable universally by keys across all namespaces, so I'd not waste it carelessly. :)

**Comment by waldbauer-certat** [comment]
Hey :wave: 

During my research on how IntelMQ could use UUIDs, I stumbled across Sonyflake. It is based on the Snowflake method first published by Twitter. Thereby not only the timestamp but also other data is stored

```
39 bits for time in units of 10 msec
 8 bits for a sequence number
16 bits for a machine id
```

This method has advantages and disadvantages, but a big advantage is the traffic saving. We would combine 3 functions of a UUID in one field.
- The uniqueness
- The exact time tracking
- The origin of the package

Instead of
```
{
	__meta: {
		UUID: "aaaaa-bbbb-cccc-ddddd-eeeee",
		Timestamp: "2021-07-21T10:20:14Z",
		Origin: "cert-at"	
	}
}
```
would result in
```
{
	__meta: {
		UUID: "2446744073709551615"
	}
}
```

If we were to decompose this UUID now, we would have the exact timestamp, the Origin as well as a sequence number.
Unfortunately, when assigning the OriginId, a central location would have to be set up, one of the few disadvantages.

Sonyflake https://github.com/sony/sonyflake

**Comment by aaronkaplan** [comment]
Solved after the discussions on the 25th of June 2022 (intelmq call) as well as defined in all clarity in a0c00a561c5d916fd9bcd3b8423a217a00ef1d7d and as well as in https://github.com/certtools/ieps/blob/main/004/UUID.md

UUIDv4 is good enough for now.
